# Generated by Django 3.0.7 on 2020-12-20 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(verbose_name='Address of bookmark')),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_accessed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emailhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Details of event')),
                ('addendum', models.TextField(blank=True, null=True, verbose_name='Addendum')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_live', models.BooleanField(default=True)),
                ('status_now', models.CharField(blank=True, max_length=20, null=True)),
                ('sameday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medreading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('HbA1c', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('blood_pressure_1', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('blood_pressure_2', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('HDL', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('LDL', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('is_live_sender', models.BooleanField(default=True)),
                ('is_live_recipient', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sent_date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('is_live', models.BooleanField(default=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('backgroundcolour', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('lime', 'lime'), ('blue', 'blue'), ('yellow', 'yellow'), ('aqua', 'aqua'), ('fuchsia', 'fuchsia'), ('green', 'green'), ('teal', 'teal'), ('purple', 'purple'), ('navy', 'navy'), ('orange', 'orange'), ('silver', 'silver')], max_length=20, verbose_name='Background Colour')),
                ('datecolour', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('lime', 'lime'), ('blue', 'blue'), ('yellow', 'yellow'), ('aqua', 'aqua'), ('fuchsia', 'fuchsia'), ('green', 'green'), ('teal', 'teal'), ('purple', 'purple'), ('navy', 'navy'), ('orange', 'orange'), ('silver', 'silver')], max_length=20, verbose_name='Date Colour')),
                ('detailcolour', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('lime', 'lime'), ('blue', 'blue'), ('yellow', 'yellow'), ('aqua', 'aqua'), ('fuchsia', 'fuchsia'), ('green', 'green'), ('teal', 'teal'), ('purple', 'purple'), ('navy', 'navy'), ('orange', 'orange'), ('silver', 'silver')], max_length=20, verbose_name='Detail Colour')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('last_accessed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem1', to='mysite.Category')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem2', to='mysite.Category')),
                ('category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem3', to='mysite.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bookmark', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Bookmark')),
                ('emailhost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Emailhost')),
                ('identifier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Identifier')),
                ('identifier2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Identifier2')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat1', to='mysite.Category'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat2', to='mysite.Category'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat3', to='mysite.Category'),
        ),
    ]
