# Generated by Django 3.0.2 on 2020-05-22 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(default='http://', verbose_name='Address of bookmark')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('specification', models.CharField(default='#000000', max_length=20)),
                ('lightness', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colourscheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('backgroundcolour', models.CharField(default='#000000', max_length=20)),
                ('datecolour', models.CharField(default='#000000', max_length=20)),
                ('detailcolour', models.CharField(default='#000000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emailhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Details of event')),
                ('addendum', models.TextField(blank=True, null=True, verbose_name='Addendum')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_live', models.BooleanField(default=True)),
                ('status_now', models.CharField(blank=True, max_length=20, null=True)),
                ('sameday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medreading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('HbA1c', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('blood_pressure_1', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('blood_pressure_2', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('HDL', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('LDL', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('is_live_sender', models.BooleanField(default=True)),
                ('is_live_recipient', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sent_date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('is_live', models.BooleanField(default=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('datecolour', models.CharField(default='black', max_length=20)),
                ('detailcolour', models.CharField(default='green', max_length=20)),
                ('backgroundcolour', models.CharField(default='yellow', max_length=20)),
                ('backgroundcolourlightness', models.IntegerField(null=True)),
                ('backgroundcolourx', models.CharField(blank=True, max_length=20, null=True)),
                ('backgroundcolourlightnessx', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bookmark', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Bookmark')),
                ('emailhost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Emailhost')),
                ('identifier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Identifier')),
                ('identifier2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Identifier2')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='mysite.Category'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='mysite.Category'),
        ),
    ]
