# Generated by Django 3.0.7 on 2021-02-04 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_auto_20201220_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(blank=True, default='', null=True, verbose_name='Notice')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of the event, in the format "yyyy-mm-dd", e.g. for 31st December 2015, enter "2015-12-31"')),
                ('detail_public', models.CharField(blank=True, default='', max_length=200, verbose_name='Title of event, this be shown publicly')),
                ('detail_private', models.TextField(blank=True, null=True, verbose_name='Details of event')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_live', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorzz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
