# Generated by Django 3.0.2 on 2020-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_event_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='notes',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='site',
            name='backgroundcolourlightness',
        ),
        migrations.RemoveField(
            model_name='site',
            name='backgroundcolourlightnessx',
        ),
        migrations.RemoveField(
            model_name='site',
            name='backgroundcolourx',
        ),
        migrations.AlterField(
            model_name='site',
            name='backgroundcolour',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('lime', 'lime'), ('blue', 'blue'), ('yellow', 'yellow'), ('aqua', 'aqua'), ('fuchsia', 'fuchsia'), ('green', 'green'), ('teal', 'teal'), ('purple', 'purple'), ('navy', 'navy'), ('orange', 'orange'), ('silver', 'silver')], max_length=20, verbose_name='Background Colour'),
        ),
        migrations.AlterField(
            model_name='site',
            name='datecolour',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('lime', 'lime'), ('blue', 'blue'), ('yellow', 'yellow'), ('aqua', 'aqua'), ('fuchsia', 'fuchsia'), ('green', 'green'), ('teal', 'teal'), ('purple', 'purple'), ('navy', 'navy'), ('orange', 'orange'), ('silver', 'silver')], max_length=20, verbose_name='Date Colour'),
        ),
        migrations.AlterField(
            model_name='site',
            name='detailcolour',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('lime', 'lime'), ('blue', 'blue'), ('yellow', 'yellow'), ('aqua', 'aqua'), ('fuchsia', 'fuchsia'), ('green', 'green'), ('teal', 'teal'), ('purple', 'purple'), ('navy', 'navy'), ('orange', 'orange'), ('silver', 'silver')], max_length=20, verbose_name='Detail Colour'),
        ),
    ]
