# Generated by Django 3.0.7 on 2021-02-04 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_e_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
