# Generated by Django 3.0.6 on 2020-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200522_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
