# Generated by Django 3.0.6 on 2020-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_photo_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colour',
        ),
        migrations.DeleteModel(
            name='Colourscheme',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='emailhost',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='emailhost',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='test',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='identifier2',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='identifier2',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='login',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='login',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='test',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.URLField(verbose_name='Address of bookmark'),
        ),
    ]
