# Generated by Django 3.0.7 on 2021-02-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210204_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e',
            name='detail_public',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Title of event, this be shown publicly'),
        ),
        migrations.AlterField(
            model_name='e',
            name='is_live',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
