# Generated by Django 3.0.6 on 2020-06-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200606_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat1', to='mysite.Category'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat2', to='mysite.Category'),
        ),
    ]
