# Generated by Django 3.0.7 on 2021-02-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210204_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e',
            old_name='detail_public',
            new_name='detail',
        ),
    ]
