# Generated by Django 3.0.6 on 2020-06-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200606_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='subcategory',
        ),
    ]
