# Generated by Django 3.0.7 on 2021-02-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210205_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='E',
        ),
    ]
