# Generated by Django 3.0.7 on 2021-02-05 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_delete_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Details of event')),
                ('addendum', models.TextField(blank=True, null=True, verbose_name='Addendum')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_live', models.BooleanField(default=True)),
                ('status_now', models.CharField(blank=True, max_length=20, null=True)),
                ('sameday', models.BooleanField(default=False)),
            ],
        ),
    ]
