# Generated by Django 3.0.7 on 2021-02-06 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_event_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_old',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='event_old',
            name='is_live',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
