# Generated by Django 3.0.7 on 2020-06-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200610_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat3', to='mysite.Category'),
        ),
    ]
