# Generated by Django 3.1.7 on 2021-05-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medreading',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='HDL',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='HbA1c',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='LDL',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='blood_pressure_1',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='blood_pressure_2',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='glucose',
        ),
    ]
