# Generated by Django 3.0.7 on 2020-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_bookmark_category3'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailhost',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identifier',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identifier2',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
